/** Create each travel record as a single field vs multiple fields **/
    CREATE or REPLACE temporary TABLE single_string_travel_review AS 
    SELECT CONCAT('The Category is ', IFNULL(CATEGORY, ' Category is not known'), '.'
        , ' Attraction Name: ', IFNULL(NAME_OF_ACTIVITY_DESTINATION_RESTAURANT, 'unknown'), '.'
        , ' The website associated with the attraction is ', IFNULL(WEBSITE, 'unknown'), '.'
        , ' Price Range: ', IFNULL(PRICE_RANGE, 'unknown'), '.'
        , ' Hours of operation: ', IFNULL(HOURS_OF_OPERATION, 'unknown'), '.'
        , ' Are Reservations Required or Not: ', IFNULL(RESERVATION_REQUIRED, 'unknown'), '.'
        , ' Activity Description: ', IFNULL(DETAILED_DESCRIPTION, 'unknown'), '.'
        , ' Comments on the Experience: ', IFNULL(COMMENTS_ON_THE_EXPERIENCE, 'unknown'), '.'
        , ' What to expect: ', IFNULL(WHAT_TO_EXPECT, 'unknown'), '.'
        , ' Additional Information: ', IFNULL(ADDITIONAL_INFORMATION, 'unknown'), '.'
        , ' Cancellation Policy: ', IFNULL(CANCELLATION_POLICY, 'unknown'), '.'
        , ' Featured Review: ', IFNULL(FEATURED_REVIEW, 'unknown'), '.'
        , ' Awards and Accolades: ', IFNULL(AWARDS_AND_ACCOLADES, 'unknown'), '.'
        , ' User Rating: ', IFNULL(USER_RATING, 'unknown'), '.'
        , ' Distance Travel Time considerations: ', IFNULL(DISTANCE_AND_TRAVEL_TIME_FROM_THE_CITY_CENTER, 'unknown'), '.'
        , ' Social Media Accounts: ', IFNULL(SOCIAL_MEDIA_ACCOUNTS, 'unknown'), '.'
        , ' Address: ', IFNULL(ADDRESS, 'unknown'), '.'
        , ' City: ', IFNULL(CITY, 'unknown'), '.'
        , ' Country: ', IFNULL(COUNTRY, 'unknown'), '.'
        , ' Contact Email: ', IFNULL(CONTACT_EMAIL, 'unknown'), '.'
        , ' Post Code: ', IFNULL(POSTAL_CODE, 'unknown'), '.'
        , ' Phone: ', IFNULL(PHONE, 'unknown'), '.'
        , ' Accessibility options available: ', IFNULL(ACCESSIBILITY, 'unknown'), '.'
        , ' Languages Spoken: ', IFNULL(LANGUAGES_SPOKEN, 'unknown'), '.'
        , ' Booking Options: ', IFNULL(BOOKING_OPTIONS, 'unknown'), '.'
        , ' Special Events and Seasonal Activities: ', IFNULL(SPECIAL_EVENTS_OR_SEASONAL_ACTIVITIES, 'unknown'), '.'
        , ' Nearby Attractions: ', IFNULL(NEARBY_ATTRACTIONS, 'unknown'), '.'
        , ' Parking Availability: ', IFNULL(PARKING_AVAILABILITY, 'unknown'), '.'
        , ' Map Coordinates: ', IFNULL(MAP_COORDINATES, 'unknown'), '.'
        , ' Photography Policy: ', IFNULL(PHOTOGRAPHY_POLICY, 'unknown'), '.'
        , ' Dress Code: ', IFNULL(DRESS_CODE, 'unknown'), '.'
        , ' Menu Highlights: ', IFNULL(MENU_HIGHLIGHTS, 'unknown'), '.'
        , ' Cuisine Type: ', IFNULL(CUISINE_TYPE, 'unknown'), '.'
        , ' Dietary Options: ', IFNULL(DIETARY_OPTIONS, 'unknown'), '.'
        , ' Capacity and Seating: ', IFNULL(CAPACITY_AND_SEATING, 'unknown'), '.'
        , ' Child Friendly Features: ', IFNULL(CHILD_FRIENDLY_FEATURES, 'unknown'), '.'
        , ' Safety information: ', IFNULL(SAFETY_INFORMATION, 'unknown'), '.'
         , ' Historical Significance or Insight: ', IFNULL(HISTORICAL_SIGNIFICANCE_OR_INSIGHT, 'unknown'), '.'
    ) AS activity_information FROM amsterdam;
